15st1 [2716][MIG] partner_name_hide_parent
qrtl/mi7-custom pull request #180
Opened 2022-09-13 05:58 UTC by kanda999

[2716](https://www.quartile.co/web?#id=2716&action=771&model=project.task&view_type=form&menu_id=505)

2022-09-13 06:07 UTC, kanda999 commented
We may want to put the module in the OCA as appropriate.
What do you think about this module fuction? @AungKoKoLin1997

2022-09-13 07:39 UTC, AungKoKoLin1997 commented
> We may want to put the module in the OCA as appropriate. What do you think ? @AungKoKoLin1997

Okay. I will create PR for this module in OCA

2022-09-13 07:45 UTC, yostashiro requested changes
Would you be able to add some explanation of in what situation this module is needed?

2022-09-13 07:45 UTC, yostashiro commented on partner_name_hide_parent/models/res_partner.py
> +        )
```suggestion
        return super()._get_contact_name(partner, name)
```

2022-09-13 07:51 UTC, yostashiro commented
> Okay. I will create PR for this module in OCA

@AungKoKoLin1997 Do not rush to do this. You must first understand and be able to explain why this module is needed.

2022-09-13 07:52 UTC, AungKoKoLin1997 commented
> > Okay. I will create PR for this module in OCA
> 
> @AungKoKoLin1997 Do not rush to do this. You must first understand and be able to explain why this module is needed.

Yes. I will trace and test first.

2022-09-13 09:35 UTC, yostashiro approved these changes
Can you please update the readme as suggested (please check and confirm the content first).

2022-09-13 09:35 UTC, yostashiro commented on partner_name_hide_parent/readme/DESCRIPTION.rst
> +* Use when you want to enter partner in account_invoice ,sale_order or others but don't want to display parent's name.
```suggestion

The function provided by this module is needed when you have to set up a child partner (e.g. a branch office of a company) as an 'individual' due to how Odoo recognizes the commercial partner (i.e. if a child partner is a 'company', the partner becomes the commercial partner itself), and you do not want to show the parent's name in QWeb report or website where the partner is referenced (if the child partner is an individual, Odoo by default shows the parent's name preceding the child's name).
```

2022-09-14 01:18 UTC, AungKoKoLin1997 commented
@kanda999 
Can I start working on this module for OCA ? Is that module in stable state?

2022-09-14 02:53 UTC, merged