15st1 [2905][ADD] account_invoice_send_mail_reply_to
qrtl/mi7-custom pull request #215
Opened 2022-10-31 10:25 UTC by AungKoKoLin1997

[2905](https://www.quartile.co/web#view_type=form&model=project.task&id=2905&active_id=2905&menu_id=)

2022-11-05 15:00 UTC, yostashiro requested changes

2022-11-05 15:00 UTC, yostashiro commented on account_invoice_send_mail_reply_to/readme/DESCRIPTION.rst
> +- Respects the 'reply-to' setting of the email template in account invoice send mail unless the value was otherwise specified.
```suggestion
- Adds reply_to field to account.account_invoice_send_wizard_form.

This adjustment is necessary for the custom module mail_compose_message_reply_to to work as expected
when an invoice is manually sent via the wizard.
```

The current description is not technically about this module.

2022-11-05 15:05 UTC, yostashiro requested changes
Please rename the module to account_invoice_send_wizard_reply_to.

Please put `account_invoice_send_views.xml` in `wizards` folder.

2022-11-07 03:34 UTC, kanda999 commented
@AungKoKoLin1997 
This module is not working as expected.
・I have tested and reply_to set is not used.
・I have confirmed that both account_invoice_send_reply_to and mail_compose_message_reply_to installed.

Because DB is made in JP??

2022-11-07 05:04 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 This module is not working as expected. ・I have tested and reply_to set is not used. ・I have confirmed that both account_invoice_send_reply_to and mail_compose_message_reply_to installed.
@kanda999 . Please watch this demo video https://drive.google.com/file/d/1JK84BSbSMSvuZpU4onSbeJGQZpTsKiXD/view?usp=share_link. I think currency you can only watch this only with 360p because google is processing this video. I suggest you to download and watch. Please let me know if something is missing.
> Because DB is made in JP??
No. My db is also created with japan.

2022-11-08 02:22 UTC, kanda999 approved these changes
Function: review: Worked as expected in mi715test11 environment.

But this module did not work in my development environment.

2022-11-10 03:35 UTC, yostashiro requested changes

2022-11-10 03:35 UTC, yostashiro commented on account_invoice_send_wizard_reply_to/README.rst
> +    :target: https://github.com/qrtl/mi7-custom/tree/15st1/account_invoice_send_wizard_reply_to
Regenerate readme for 15.0.

2022-11-11 09:08 UTC, kanda999 commented
This PR is closed because I followed up with https://github.com/qrtl/mi7-custom/pull/218

2022-11-11 09:08 UTC, closed without merging