[ADD] website_product_visibility_control_timer
qrtl/mi7-custom pull request #239
Opened 2023-02-28 03:56 UTC by AungKoKoLin1997

[3216](https://www.quartile.co/web#id=3216&action=771&model=project.task&view_type=form&menu_id=505)

2023-03-01 04:33 UTC, yostashiro requested changes
Can we change the module name to website_product_publish_cron, and propose it in OCA?

2023-03-01 04:33 UTC, yostashiro commented on website_product_visibility_control_timer/models/product_template.py
> +    def _check_website_product_visibility(self):
Add methods to return publish domain and unpublish domain for extensibility.

2023-03-01 04:33 UTC, yostashiro commented on website_product_visibility_control_timer/readme/DESCRIPTION.rst
> +- Control the visibility of products in website depend on their publish date and unpublish date.
```suggestion
This module adds expected publish/unpublish date fields to the product, and a scheduled action to publish/unpublish products according to the product settings.

This function can be useful if you run an eCommerce platform where a set of products need to be sold for a scheduled timeframe.
```

2023-03-01 04:33 UTC, yostashiro commented on website_product_visibility_control_timer/models/product_template.py
> +            ]
This domain does not work if user intends to first unpublish an already published product, and then unpublish it.  I know this scenario sounds rather unlikely, but can we handle this case also?

2023-03-01 04:33 UTC, yostashiro commented on website_product_visibility_control_timer/models/product_template.py
> +            ]
Same as above.

2023-03-29 07:17 UTC, AungKoKoLin1997 commented
This module was proposed to OCA and the next activity will be followed in OCA PR.

2023-03-29 07:17 UTC, closed without merging