st1 [1691][IMP] account_invoice_validate_send_email
qrtl/mi7-custom pull request #66
Opened 2021-07-16 06:41 UTC by TomohiroAbe-Quartile

[1691](https://www.quartile.co/web#id=1691&action=771&model=project.task&view_type=form&menu_id=505)

Previous PR
#64 

検証内容：
請求書自動送信対象外チェックについて、分納に対応。
以下を受注・返品の両方で検証。

- 請求書行が2行ある受注を作成。発送を1行ずつに分けて検証。
1行目の発送では請求書自動送信対象外にチェック、2行目の発送にはチェックを入れずに検証をクリック。
1行目発送の請求書→メール送信されず。
2行目発送の請求書→メールが送信。

2021-07-16 06:48 UTC, yostashiro requested changes

2021-07-16 06:48 UTC, yostashiro commented on account_invoice_validate_send_email/models/account_invoice.py
> +                )
```suggestion
                if orders:
                    pickings = self.env["stock.picking"].search(
                        [("sale_id", "in", orders.ids)]
                    )
```
Sorry I didn't catch this earlier.

2021-07-16 06:48 UTC, yostashiro commented on account_invoice_validate_send_email/models/account_invoice.py
> +            if not pickings:
```suggestion
            # Supposedly 返品伝票
            if not pickings:
```

2021-07-16 07:34 UTC, TomohiroAbe-Quartile commented on account_invoice_validate_send_email/models/account_invoice.py
> +                )
Thank you, I forgot too.

2021-07-16 07:34 UTC, TomohiroAbe-Quartile commented on account_invoice_validate_send_email/models/account_invoice.py
> +            if not pickings:
Thank you, I added

2021-07-22 07:28 UTC, yostashiro approved these changes
Travis fails due to the issue reported in task [1730](https://www.quartile.co/web#id=1730&action=771&model=project.task&view_type=form&menu_id=505).

There is no quick fix to the situation, and we should go ahead with merge.  The tests passed in my dev environment.

2021-07-24 04:58 UTC, merged